export const status = {
  INIT_CHECKING: '等待系统审核',
  INIT_CHECK_FAILED: '系统审核失败',
  RECHECKING: '审核中',
  RECHECK_FAILED: '审核未通过',
  RIGHT_AUTHENTICING: '等待国家版权局确权',
  RIGHT_AUTHENTIC_FAILED: '确权失败',
  RIGHT_AUTHENTIC_SUCCEED: '确权成功',
  UNCOMMITTED: '未提交申请',
  TRANSACTED: '已获取版权及区块链编号',
};

export const types = {
  ALL: '全部',
  AUDIO: '音频',
  VIDEO: '视频',
  WORD: '文字',
  PICTURE: '图片',
};

export const compositionFields = {
  // 前端添加
  count: '购买的数量',
  item_type: '购买的方式',
  // 后端返回
  audit_at: '审核时间',
  audit_msg: '审核意见',
  auditor: '审核人',
  certification_url: '证明材料',
  completed_at: '完成时间',
  completed_site: '完成地点',
  composition_url: '作品链接',
  copyright_id: '国家标准版权编码',
  copyright_owner: '版权所有者',
  cover_url: '封面链接',
  created_at: '申请时间',
  created_by: '',
  desc: '简要描述',
  id: '',
  name: '作品名称',
  price: '发行价格',
  published_at: '出版时间',
  publisher: '出版单位',
  recommend_max_price: '推荐最大价格',
  recommend_min_price: '推荐最小价格',
  release_at: '发行时间',
  sold_count: '购买次数',
  sold_out: '是否下架',
  status: '状态',
  total_count: '发行数量',
  remain_count: '库存量',
  transaction_at: '上链时间',
  transaction_id: '上链编号',
  type: '作品类型',
  updated_by: '',
  user_id: '',
  view_count: '浏览次数',
  author: '作者',
  composition_id: '',
  cutter: '剪辑师',
  director: '导演',
  effector: '特效师',
  lyric_author: '词作者',
  main_actor: '主演',
  music_author: '曲作者',
  photographer: '摄影师',
  script_writer: '编剧',
  singer: '演唱者',
  sound_recorder: '录音师',
  updated_at: '',
  video_producer: '制片人',
};

export const detailKey = [
  'author',
  'composition_id',
  'created_at',
  'cutter',
  'director',
  'effector',
  'lyric_author',
  'main_actor',
  'music_author',
  'photographer',
  'script_writer',
  'singer',
  'sound_recorder',
  'updated_at',
  'video_producer',
];

export const formMessage = {
  name: { required: true, message: '请填写一个作品名称' },
  type: { required: true, message: '请选择作品类型' },
  copyright_owner: { required: true, message: '请填写一个版权所有人' },
  lyric_author: { required: true, message: '请填写一个作词人' },
  music_author: { required: true, message: '请填写一个作曲人' },
  singer: { required: true, message: '请填写一个演唱者' },
  sound_recorder: { required: true, message: '请填写一个录音' },
  completed_at: { required: true, message: '请选择一个时间' },
  composition_url: { required: true, message: '请上传作品' },
  published_at: { required: false, message: '请选择一个时间' },
  copyright_id: { required: false, message: '国家标准版权编码' },
  desc: { required: false, message: '简要描述' },
  video_producer: { required: true, message: '请填写一个制片人' },
  script_writer: { required: true, message: '请填写一个编剧' },
  director: { required: true, message: '请填写一个导演' },
  main_actor: { required: true, message: '请填写一个主要演员' },
  photographer: { required: true, message: '请填写一个摄影' },
  cutter: { required: true, message: '请填写一个剪辑' },
  effector: { required: true, message: '请填写一个特效' },
  author: { required: true, message: '请填写一个作者' },
  completed_site: { required: true, message: '请选择一个完成地点' },
};
