export const HOME_LIST_GET_ALL = 'HOME_LIST_GET_ALL';

export const HOME_LIST_GET_LIST = 'HOME_LIST_GET_LIST';

export const HOME_LIST_GET_LIST_SUCCESS = 'HOME_LIST_GET_LIST_SUCCESS';

export type HOME_LIST_GET_LIST_SUCCESS = typeof HOME_LIST_GET_LIST_SUCCESS;

export const HOME_LIST_GET_LIST_ERROR = 'HOME_LIST_GET_LIST_ERROR';

export const HOME_LIST_GET_TYPE = 'HOME_LIST_GET_TYPE';

export type HOME_LIST_GET_TYPE = typeof HOME_LIST_GET_TYPE;

// reducer
export const HOME_LIST_SAVE = 'HOME_LIST_SAVE';

export type HOME_LIST_SAVE = typeof HOME_LIST_SAVE;

export const HOME_LIST_DELETE = 'HOME_LIST_DELETE';

export type HOME_LIST_DELETE = typeof HOME_LIST_DELETE;
