export const SHOPPING_CARD_ADD = 'SHOPPING_CARD_ADD';

export type SHOPPING_CARD_ADD = typeof SHOPPING_CARD_ADD;

export const SHOPPING_CARD_DETAIL = 'SHOPPING_CARD_DETAIL';

export const SHOPPING_CARD_DETAIL_SUCCESS = 'SHOPPING_CARD_DETAIL_SUCCESS';

export type SHOPPING_CARD_DETAIL_SUCCESS = typeof SHOPPING_CARD_DETAIL_SUCCESS;

export const SHOPPING_CARD_DETAIL_ERROR = 'SHOPPING_CARD_DETAIL_ERROR';

// REDUCER
export const CHANGE_SHOPPING = 'CHANGE_SHOPPING';

export type CHANGE_SHOPPING = typeof CHANGE_SHOPPING;
